import { Sidebar } from "../../../components";
import type { SidebarSection } from "../../../components";

// Where the reader can go from here, in the order the library is learned: the one thing that has
// to be done before any of it can be used, the primitives everything else is drawn by, and then
// the components themselves. It is read down rather than picked over, so the links are written
// without icons, which would say nothing the labels have not already said
const sections: SidebarSection[] = [
    {
        title: "Getting Started",
        links: [{ label: "Installation", href: "/getting-started/installation" }],
    },
    {
        title: "Primitives",
        links: [
            { label: "Color", href: "/primitives/color" },
            { label: "Size", href: "/primitives/size" },
            { label: "Typography", href: "/primitives/typography" },
        ],
    },
    {
        title: "Components",
        // Every component the library exports, named as it is imported
        links: [
            { label: "Accordion", href: "/components/accordion" },
            { label: "Action Bar", href: "/components/action-bar" },
            { label: "Action List", href: "/components/action-list" },
            { label: "Action Menu", href: "/components/action-menu" },
            { label: "Alert", href: "/components/alert" },
            { label: "Anchored Overlay", href: "/components/anchored-overlay" },
            { label: "Aspect Ratio", href: "/components/aspect-ratio" },
            { label: "Attachment", href: "/components/attachment" },
            { label: "Autocomplete", href: "/components/autocomplete" },
            { label: "Avatar", href: "/components/avatar" },
            { label: "Avatar Stack", href: "/components/avatar-stack" },
            { label: "Banner", href: "/components/banner" },
            { label: "Blankslate", href: "/components/blankslate" },
            { label: "Blockquote", href: "/components/blockquote" },
            { label: "Box", href: "/components/box" },
            { label: "Breadcrumbs", href: "/components/breadcrumbs" },
            { label: "Bubble", href: "/components/bubble" },
            { label: "Button", href: "/components/button" },
            { label: "Button Group", href: "/components/button-group" },
            { label: "Calendar", href: "/components/calendar" },
            { label: "Card", href: "/components/card" },
            { label: "Caret", href: "/components/caret" },
            { label: "Carousel", href: "/components/carousel" },
            { label: "Chart", href: "/components/chart" },
            { label: "Checkbox", href: "/components/checkbox" },
            { label: "Checkbox Card", href: "/components/checkbox-card" },
            { label: "Checkbox Group", href: "/components/checkbox-group" },
            { label: "Clipboard", href: "/components/clipboard" },
            { label: "Code", href: "/components/code" },
            { label: "Code Block", href: "/components/code-block" },
            { label: "Collapsible", href: "/components/collapsible" },
            { label: "Combobox", href: "/components/combobox" },
            { label: "Command Palette", href: "/components/command-palette" },
            { label: "Confirmation Dialog", href: "/components/confirmation-dialog" },
            { label: "Context Menu", href: "/components/context-menu" },
            { label: "Counter Label", href: "/components/counter-label" },
            { label: "Data Table", href: "/components/data-table" },
            { label: "Date Picker", href: "/components/date-picker" },
            { label: "Details", href: "/components/details" },
            { label: "Dialog", href: "/components/dialog" },
            { label: "Drawer", href: "/components/drawer" },
            { label: "Em", href: "/components/em" },
            { label: "Empty State", href: "/components/empty-state" },
            { label: "File Upload", href: "/components/file-upload" },
            { label: "Filtered Action List", href: "/components/filtered-action-list" },
            { label: "Floating Panel", href: "/components/floating-panel" },
            { label: "Flow", href: "/components/flow" },
            { label: "Form Control", href: "/components/form-control" },
            { label: "Format Byte", href: "/components/format-byte" },
            { label: "Format Number", href: "/components/format-number" },
            { label: "Frame", href: "/components/frame" },
            { label: "Header", href: "/components/header" },
            { label: "Heading", href: "/components/heading" },
            { label: "Hidden", href: "/components/hidden" },
            { label: "Highlight", href: "/components/highlight" },
            { label: "Hover Card", href: "/components/hover-card" },
            { label: "Icon Button", href: "/components/icon-button" },
            { label: "Image", href: "/components/image" },
            { label: "Inline Message", href: "/components/inline-message" },
            { label: "Keybinding Hint", href: "/components/keybinding-hint" },
            { label: "Label", href: "/components/label" },
            { label: "Label Group", href: "/components/label-group" },
            { label: "Layer Card", href: "/components/layer-card" },
            { label: "Link", href: "/components/link" },
            { label: "Link Button", href: "/components/link-button" },
            { label: "List", href: "/components/list" },
            { label: "Map", href: "/components/map" },
            { label: "Mark", href: "/components/mark" },
            { label: "Markdown", href: "/components/markdown" },
            { label: "Marquee", href: "/components/marquee" },
            { label: "Message", href: "/components/message" },
            { label: "Meter", href: "/components/meter" },
            { label: "Native Select", href: "/components/native-select" },
            { label: "Navigation List", href: "/components/navigation-list" },
            { label: "Navigation Menu", href: "/components/navigation-menu" },
            { label: "Number Input", href: "/components/number-input" },
            { label: "Page Layout", href: "/components/page-layout" },
            { label: "Pagination", href: "/components/pagination" },
            { label: "Password Input", href: "/components/password-input" },
            { label: "PIN Input", href: "/components/pin-input" },
            { label: "Placeholder", href: "/components/placeholder" },
            { label: "Popover", href: "/components/popover" },
            { label: "Portal", href: "/components/portal" },
            { label: "Progress Bar", href: "/components/progress-bar" },
            { label: "Progress Circle", href: "/components/progress-circle" },
            { label: "QR Code", href: "/components/qr-code" },
            { label: "Radio", href: "/components/radio" },
            { label: "Radio Card", href: "/components/radio-card" },
            { label: "Radio Group", href: "/components/radio-group" },
            { label: "Rating", href: "/components/rating" },
            { label: "Relative Time", href: "/components/relative-time" },
            { label: "Resizable", href: "/components/resizable" },
            { label: "Rich Text Editor", href: "/components/rich-text-editor" },
            { label: "Scrollable Region", href: "/components/scrollable-region" },
            { label: "Segmented Control", href: "/components/segmented-control" },
            { label: "Select", href: "/components/select" },
            { label: "Select Panel", href: "/components/select-panel" },
            { label: "Separator", href: "/components/separator" },
            { label: "Skeleton Avatar", href: "/components/skeleton-avatar" },
            { label: "Skeleton Box", href: "/components/skeleton-box" },
            { label: "Skeleton Text", href: "/components/skeleton-text" },
            { label: "Slider", href: "/components/slider" },
            { label: "Spinner", href: "/components/spinner" },
            { label: "Stack", href: "/components/stack" },
            { label: "State Label", href: "/components/state-label" },
            { label: "Statistic Card", href: "/components/statistic-card" },
            { label: "Status", href: "/components/status" },
            { label: "Steps", href: "/components/steps" },
            { label: "Swap", href: "/components/swap" },
            { label: "Tabs", href: "/components/tabs" },
            { label: "Text", href: "/components/text" },
            { label: "Text Input", href: "/components/text-input" },
            { label: "Textarea", href: "/components/textarea" },
            { label: "Timeline", href: "/components/timeline" },
            { label: "Toast", href: "/components/toast" },
            { label: "Toggle Switch", href: "/components/toggle-switch" },
            { label: "Token", href: "/components/token" },
            { label: "Tooltip", href: "/components/tooltip" },
            { label: "Topic Tag", href: "/components/topic-tag" },
            { label: "Tour", href: "/components/tour" },
            { label: "Tree View", href: "/components/tree-view" },
            { label: "Truncate", href: "/components/truncate" },
        ],
    },
];

// The column of links standing beside the page. The row across the top already says what the site
// is, so the heading naming the list is left to a screen reader rather than said a second time
const HomeSidebar = () => <Sidebar heading="Base UI" hideHeading sections={sections} />;

export default HomeSidebar;
